spring:
  application:
    name: notification-service
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3307/parkease_notifications?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: parkease_user
    password: parkease_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: ayushrathour3122@gmail.com
    password: nkffcuxxdraiwgci
    from: ${spring.mail.username}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost

jwt:
  secret: "2dEC87cE0KSPZmT1nH4+T5FaB35+6+F/omeu3Qlxnvg="

twilio:
  account-sid: your-account-sid
  auth-token: your-auth-token
  phone-number: +1234567890

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
